apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-pod
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongo-pod
    spec:
      containers:
      - name: mongodb-container
        image: mongo
        env: 
        - name: MONGO_INITDB_DATABASE
          value: database
        ports:
        - containerPort: 27017 
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-pod
