apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-deployment
  labels:
    app: mongo-deployment
spec:
  serviceName: "mongo-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-pod
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongo-pod
    spec:
      containers:
      - name: mongodb-container
        image: mongo
        env: 
        - name: MONGO_INITDB_DATABASE
          value: database
        ports:
        - containerPort: 27017 
        volumeMounts:
          - name: data-volume
            mountPath: /data/db
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: mongo-data
