version: "3"
services:

  mongodb:
    container_name: mongodb
    image: mongo
    command: mongod --auth
    restart: unless-stopped
    env_file: ./envfiles/DB.env
    ports:  
      - 27017:27017
    networks:
      - private
    volumes:
      - /Read-it/mongoData:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  backend:
    container_name: node
    restart: unless-stopped
    image: waer/backend:latest
    env_file: ./envfiles/backend.env
    networks:
      - frontend_net
      - private
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    links:
      - mongodb
    volumes:
      - /Read-it/Backend/log:/usr/src/app/log
    stdin_open: true
    tty: true

    
  frontend:
    container_name: Frontend
    image: waer/frontend:latest
    env_file: ./envfiles/frontend.env
    networks:
      - frontend_net
    depends_on:
      - backend
    ports:
      - 5000:5000
      - 80:80
      # - 443:443
    restart: always
    # volumes:
    #   - ./nginx/conf/:/etc/nginx/conf.d/:ro
    #   - ./certbot/www:/var/www/certbot/:ro


networks:
  private:
  frontend_net: