version: "3"
services:

  mongodb_test:
    container_name: mongodb_test
    image: mongo
    command: mongod --auth
    restart: unless-stopped
    env_file: ./envfiles/DB.env
    networks:
      - private_test
    volumes:
      - /Read-it-testing/mongoData:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  backend:
    container_name: node_test
    restart: unless-stopped
    image: waer/backend:latest
    env_file: ./envfiles/backend.env
    networks:
      - frontend_test_net
      - private_test
    depends_on:
      - mongodb_test
    links:
      - mongodb_test
    volumes:
       - /Read-it-testing/Backend/log/access.log:/usr/src/app/access.log
    stdin_open: true
    tty: true

    
  frontend_test:
    container_name: frontend_test
    image: waer/frontend:latest
    env_file: ./envfiles/frontend.env
    networks:
      - frontend_test_net
    depends_on:
      - backend
    restart: always

  cypress:
    image: waer/web_testing
    depends_on:
      - frontend_test
    environment:
      - CYPRESSBASEURL=http://frontend_test
    networks:
      - frontend_test_net
    working_dir: /home/node/app
    command: npx cypress run
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: 2G


networks:
  private_test:
  frontend_test_net: