version: "3"
services:


  frontend_test:
    image: nginx
    networks:
      - private_test
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  mongodb_test:
    image: mongo
    command: mongod --auth
    restart: unless-stopped
    env_file: ./envfiles/DB.env
    networks:
      - private_test
    volumes:
      - ../mongoData:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    

  backend:
    restart: unless-stopped
    image: waer/backend:latest
    env_file: ./envfiles/backend.env
    networks:
      - private_test
    depends_on:
      - mongodb_test
    links:
      - mongodb_test
    volumes:
      - /Read-it/Backend/images/:/usr/src/app/images
      - /Read-it/Backend/log/:/usr/src/app/logs
      - /Read-it/Backend/videos/:/usr/src/app/videos
      - /Read-it/Backend/private:/usr/src/app/private
    
  frontend:
    image: waer/frontend:latest
    env_file: ./envfiles/frontend.env
    networks:
      - private_test
    depends_on:
      - backend
    restart: always


  cypress:
    image: waer/web_testing
    depends_on:
      - frontend_test
    environment:
      - CYPRESSBASEURL=http://frontend_test
    networks:
      - private_test
    working_dir: /home/node/app
    command: npx cypress run
    deploy:
      resources:
        limits:
          cpus: 0.8
          memory: 4G


networks:
  private_test: