- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Add Docker Group
    group: name=docker state=present

  - name: Install required system packages
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: latest
      update_cache: true

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Add remote "ubuntu" user to "docker" group
    user:
      name: root
      group: docker
      append: yes
  
  - name: Install Docker compose
    pip:
      name: docker-compose

  - name: Ensure jenkins directory on docker host
    file:
      state: directory
      owner: "1000"
      group: "1000"
      path: /share/jenkins

  - name: Pull the latest official jenkins docker image
    docker_image:
      name: "jenkins/jenkins:lts"

  - name: copy jenkins image
    become: true 
    copy:
      src: /mnt/d/Created_by_me/SW_Reops/SW-DevOps/DockerFiles/Dockerfile
      dest: /Read-it/JenkinsDockerFile/
      owner: root
      group: root
      mode: '0644'

  - name: build docker_jenkins image
    community.docker.docker_image:
      build:
        path: /Read-it/JenkinsDockerFile/
      name: docker_jenkins
      tag: v1
      source: build


  - name: Create Docker Jenkins Container
    docker_container:
      name: jenkins
      image: docker_jenkins:v1
      ports:
       - "8080:8080"
       - "50000:50000"
      volumes:
       - "jenkins_home:/var/jenkins_home"
       - "/var/run/docker.sock:/var/run/docker.sock"
      state: started


# ansible-playbook -i hosts /mnt/d/Created_by_me/SW_Reops/SW-DevOps/ansible/ConfigureJenkins.yml --private-key=~/.ssh/MainVm_key.pem
# ansible all -i hosts -m ping --private-key=~/.ssh/MainVm_key.pem
# sudo docker run -p 8085:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts -d
# sudo docker exec 16f8776ff088 cat /var/jenkins_home/secrets/initialAdminPassword
# sudo docker stop 16f8776ff088