- hosts: all
  gather_facts: no
  become: true
  become_user: root
  tasks:

  - name: copying flutter code
    become: true 
    copy:
      src: /mnt/d/Created_by_me/SW_Reops/SW-CrossPlatform/
      dest: /FlutterTesting

# ssh -i ~/.ssh/MainVm_key.pem azureuser@read-it.francecentral.cloudapp.azure.com
# ansible-playbook -i hosts /mnt/d/Created_by_me/SW_Reops/SW-DevOps/ansible/transferflutter.yaml --private-key=~/.ssh/MainVm_key.pem